version: 2
jobs:
  build:
    working_directory: ~/linux_practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: ls
      - run:
          working_directory: circleci_dir
          command: sudo pip install -r requirements.txt
      - run:
          name: ウェエエえええええええい！！！！
          working_directory: circleci_dir
          command: nosetests tests/match-test.py