version: 2
jobs:
  build:
    working_directory: ~/linux_practice
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          working_directory: circleci_dir
          name: ディレクトリ確認
          command: ls
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: nosetests tests/math-test.py