# Linuxでの実装
# $ yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
# $ yum-config-manager --enable docker-ce-nightly
# $ yum install -y docker-ce docker-ce-cli containerd.io
# systemctl start docker
# status docker